l_english:
 PRODUCTION_PRODUCTION_LABEL:0 "生產"
 PRODUCTION_EQUIPMENTPOOL_LABEL:0 "庫存"
 PRODUCTION_EFFICIENCY_LABEL:0 "§T效率§!"
 PRODUCTION_EQUIPMENT_LABEL:0 "裝備"
 PRODUCTION_ADJUSTERS_LABEL:0 "修正"
 PRODUCTION_MATERIALS_LABEL:0 "原料"
 PRODUCTION_FACTORIES_LABEL:0 "工業"
 PRODUCTION_OPERATIONAL_ARMS_FACTORIES_LABEL:0 "軍事工廠"
 PRODUCTION_OPERATIONAL_DOCKYARDS_LABEL:0 "海軍船塢"
 PRODUCTION_OPERATIONAL_FACTORIES_LABEL:0 "民生工廠"
 PRODUCTION_OPERATIONAL_DOCKYARDS_LABEL_SHORT:0 "海軍船塢"
 PRODUCTION_AVAILABLE_ARMS_FACTORIES_LABEL:0 "閒置的軍事工廠"
 PRODUCTION_AVAILABLE_DOCKYARDS_LABEL:0 "閒置的海軍船塢"
 PRODUCTION_AVAILABLE_FACTORIES_LABEL:0 "閒置的民生工廠"
 PRODUCTION_OPERATIONAL_FACTORIES_VALUE:0 "$VALUE$/$TOT$"
 PRODUCTION_MILITARY_LABEL:0 "§T陸上裝備與航空武裝§!"
 PRODUCTION_NAVAL_LABEL:0 "§T海軍艦艇§!"
 PRODUCTION_BUILDINGS_LABEL:0 "§T建築工程§!"
 PRODUCTION_PRODUCING_DAILY:0 "$AMOUNT$ /日"
 PRODUCTION_PRODUCING_WEEKLY:0 "$AMOUNT$ /週"
 PRODUCTION_PRODUCING_MONTHLY:0 "$AMOUNT$ /月"
 PRODUCTION_PRODUCING_YEARLY:0 "$AMOUNT$ /年"
 PRODUCTION_PRODUCING_ETA_DATE:0 "下次完成日期：$DATE$"
 PRODUCTION_REPAIRING_ETA_DATE:0 "修復完成日期：$DATE$"
 PRODUCTION_PRODUCING_ETA_DAYS:0 "每天$AMOUNT$單位"
 PRODUCTION_PRODUCING_ETA_WEEKS:0 "每週$AMOUNT$單位"
 PRODUCTION_PRODUCING_ETA_MONTHS:0 "每月$AMOUNT$單位"
 PRODUCTION_PRODUCING_ETA_YEARS:0 "每年$AMOUNT$單位"
 PRODUCTION_PRODUCING_NEVER:1 "§R無限§!"
 PRODUCTION_PRODUCING_NO_FACTORIES:0 "§R有閒置中的工廠§!"
 PRODUCTION_PRODUCING_NONE:0 "§R無§!"
 PRODUCTION_CAN_NOT_DEPLOY:0 "§R無法部署§!"
 PRODUCTION_CAN_NOT_DEPLOY_MANPOWER:0 "人力不足"
 PRODUCTION_INCREASE_PRIORITY_LABEL:0 "§G點擊左鍵，即可§H增加優先權§!\n按住「§GShift§!」同時§G點擊左鍵§!，即可設置§H最高優先權§!。§!"
 PRODUCTION_DECREASE_PRIORITY_LABEL:0 "§G點擊左鍵，即可§H減少優先權§!\n按住「§GShift§!」同時§G點擊左鍵§!，即可設置§H最低優先權§!。§!"
 PRODUCTION_PRIORITY_DELAYED:0 "相對於級別較低的生產線，戰略資源會優先發配給級別較高的生產線。"
 PRODUCTION_EFFICIENCY:0 "£prod_eff §T生產效率：$AMOUNT|H1%$§!"
 PRODUCTION_EFFICIENCY_MOD:0 "£prod_eff §T生產效率：$AMOUNT|Y1%$§!\n"
 PRODUCTION_EFFICIENCY_WITH_GAIN:2 "£prod_eff §T生產效率：$AMOUNT|H1%$§!（每日增幅：$GAIN|H3%$）"
 PRODUCTION_EFFICIENCY_DESC:0 "§T平均生產效率。\n每座工廠的生產效率平均提升：$VALUE|H=2$%§!"
 PRODUCTION_RESOURCE_PENALTY:0 "§T缺少戰略資源：$AMOUNT|R1%$§!"
 PRODUCTION_ASSIGN_EQUIPMENT:0 "§T分配生產項目。§!"
 PRODUCTION_MATERIALS_OIL:0 "石油"
 PRODUCTION_MATERIALS_ALUMINIUM:0 "鋁"
 PRODUCTION_MATERIALS_RUBBER:0 "橡膠"
 PRODUCTION_MATERIALS_CHROMIUM:0 "鉻"
 PRODUCTION_MATERIALS_STEEL:0 "鋼鐵"
 PRODUCTION_MATERIALS_TUNGSTEN:0 "鎢"
 PRODUCTION_MATERIAL_VAL:0 "$VALUE|0H$"
 PRODUCTION_VEHICLES_BUTTON:0 "生產戰甲車輛"
 PRODUCTION_VEHICLES_BUTTON_DISABLED:0 "§R尚未研發§!戰甲車輛"
 PRODUCTION_VEHICLES_BUTTON_NO_FACTORIES_DISABLED:0 "§R缺少閒置的軍事工廠！§!"
 PRODUCTION_INFANTRY_BUTTON:0 "生產小型槍械與大型火砲"
 PRODUCTION_INFANTRY_BUTTON_DISABLED:0 "§R尚未研發§!小型槍械與大型火砲"
 PRODUCTION_INFANTRY_BUTTON_NO_FACTORIES_DISABLED:0 "§R缺少閒置的軍事工廠！§!"
 PRODUCTION_AIRCRAFT_BUTTON:0 "生產戰鬥機和運輸機"
 PRODUCTION_AIRCRAFT_BUTTON_DISABLED:0 "§R尚未研發§!戰鬥機和運輸機"
 PRODUCTION_AIRCRAFT_BUTTON_NO_FACTORIES_DISABLED:0 "§R缺少閒置的軍事工廠！§!"
 PRODUCTION_SHIPS_BUTTON:0 "生產戰鬥艦和運輸艦"
 PRODUCTION_SHIPS_BUTTON_DISABLED:0 "§R尚未研發§!戰鬥艦和運輸艦"
 PRODUCTION_SHIPS_BUTTON_NO_DEPLOY_DISABLED:0 "§R缺少閒置的海軍基地！§!"
 PRODUCTION_SHIPS_BUTTON_NO_FACTORIES_DISABLED:0 "§R缺少閒置的海軍船塢！§!"
 PRODUCTION_CONSUMER_GOODS_VALUE:0 "$VALUE$"
 PRODUCTION_CONSUMER_GOODS:0 "日常用品"
 PRODUCTION_CONSUMER_GOODS_LABEL:0 "§H日常用品§!"
 PRODUCTION_CONSUMER_GOODS_DESC:0 "按照現行的經濟政策，人們希望有$PERCENTAGE|H0%$的工廠可以用於日常消費。只有民生工廠才能滿足這個需求，在我們剩餘的$OPERATIONAL|H$座工廠之中還有$TRADE_USABLE|H$座工廠能夠用來進行貿易。"
 PRODUCTION_CIV_AND_MIL_FACTORIES:0 "全國工廠總數：$KEY|H$"
 PRODUCTION_REQ_CONSUMER_GOODS_FACTORIES:0 "日常民生所需：$KEY|H$"
 PRODUCTION_MATERIAL_COST_DESC:0 "§T這條生產線需要消耗$AMOUNT|0H$單位$MATERIAL|H$。§!"
 PRODUCTION_MATERIAL_COST_LACKING_DESC:2 "§T這條生產線還需要$AMOUNT|0H$單位的戰略資源才能§G全速§!運轉。§!\n否則生產效率便會持續受到§R短缺§!。"
 PRODUCTION_LINE_CANCEL:3 "§G點擊左鍵，即可§H撤銷§!這條生產線§!\n按住「§GShift§!」同時§G點擊左鍵§!，即可§H撤銷§!所有生產線§!。"
 PRODUCTION_LINE_CANCEL_SHIP_REFIT:1 "§G點擊左鍵§!，即可§R撤銷§!正在進行的改裝工程。"
 PRODUCTION_CREATE_VARIANT:0 "§H衍生型號§!"
 PRODUCTION_CANCEL_CONSTRUCTION:0 "§T取消§!" #
 PRODUCTION_VARIANT_OBSOLETE_YES:1 "復役"
 PRODUCTION_VARIANT_OBSOLETE_NO:1 "退役"
 PRODUCTION_VARIANT_OBSOLETE_YES_DESC:0 "§G點擊左鍵§!，即可啟用衍生型號，並且標記為新型裝備。"
 PRODUCTION_VARIANT_OBSOLETE_NO_DESC:0 "§G點擊左鍵§!，即可停用衍生型號，並且標記為過時裝備。"
 TRADE_FACTORIES_VALUE:0 "$VALUE$/$TOT$"
 CONFIRMCANCELPRODUCTIONLINE_TITLE:0 "撤銷生產線"
 CONFIRMCANCELPRODUCTIONLINE_DESC:0 "您確定要§R撤銷§!這條生產線嗎？"
 CONFIRMCANCELALLPRODUCTIONLINE_TITLE:0 "撤銷所有生產線"
 CONFIRMCANCELALLPRODUCTIONLINE_DESC:0 "您確定要§R撤銷§!所有生產線嗎？"
 CONFIRM_SWITCH_PRODUCTION_MODEL_TITLE:0 "變更生產項目"
 CONFIRM_SWITCH_PRODUCTION_MODEL_DESC:0 "您確定要§R變更§!生產項目嗎？這將失去$DAYS|R$天的產量。"
 CONFIRMCANCELCONSTRUCTION_TITLE:0 "取消建設"
 CONFIRMCANCELCONSTRUCTION_DESC:0 "您確定要§R撤銷§!位於$REGION|H$的施工項目（$CONSTRUCTION|H$）嗎？"
 CONFIRMCANCELCONSTRUCTIONS_TITLE:0 "取消建設"
 CONFIRMCANCELCONSTRUCTIONS_DESC:0 "您確定要§R撤銷§!所有施工項目嗎？"
 INFINITY:0 "£infinity_icon"
 PRODUCTION_EQUIPMENT_NEED:0 "需要：$AMOUNT|Y$"
 PRODUCTION_DEPLOY_TO_BASE:0 "部署至港口：$BASE|H$"
 PRODUCTION_DEPLOY_TO_FLEET:1 "部署至艦隊：$FLEET|H$"
 PRODUCTION_DEPLOY_TO_RESERVE_FLEET_THEATER:1 "部署至戰區：$THEATER|H$"
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET_INVALID_BASE:0 "部署至$STATE|H$海軍基地外的「$FLEET|H$」。"
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET:1 "部署至$STATE|H$海軍基地內的「$FLEET|H$」。"
 PRODUCTION_NAVAL_DEPLOYMENT_THEATER:0 "部署至$STATE|H$的$THEATER|H$基地。"
 PRODUCTION_NAVAL_DEPLOYMENT_BASE:0 "部署$STATE|H$海軍基地。"
 PRODUCTION_NAVAL_DEPLOYMENT_INVALID_BASE:0 "無部署目標"
 PRODUCTION_NAVAL_DEPLOYMENT_NOT_DEPLOYABLE:0 "無法部署"
 PRODUCTION_NAVAL_DEPLOYMENT_AUTO_DEPLOYMENT:0 "自動"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING:0 "廢棄"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING_DESC:0 "沒有海軍基地可供部署。艦艇將於完工後被廢棄。"
 PRODUCTION_NAVAL_DEPLOYMENT_STOCKPILING:0 "庫存"
 PRODUCTION_RIGHT_CLICK_TO_ZOOM:0 "§G點擊右鍵即可快移至此處§!"
 PRODUCTION_NAVAL_DEPLOY_LIST:0 "部署目標"
 WEEKLY_PRODUCTION:0 "每週產量"
 PRODUCTION_WORKING_FACTORIES:0 "這是您目前正在生產軍事裝備的工廠數量。"
 PRODUCTION_WORKING_DOCKYARDS:0 "這是您目前正在生產海軍船艦的船塢數量。"
 PRODUCTION_WORKING_DOCKYARDS_FOR_REPAIRS:0 "這是您目前正在維修海軍船艦的船塢數量。"
 PRODICTION_MIC_TRANSFERED:0 "目前有$AMOUNT|Y$座工廠正被宗主國$OVERLORD|Y$徵用。"
 PRODICTION_MIC_RECEIVED_FROM_SUBJECT:0 "目前有$AMOUNT|Y$座工廠是從附庸國徵用來的。"
 PRODICTION_MIC_SENT_TO_OVERLORD:0 "目前有$AMOUNT|R$座工廠受到宗主國的徵用，剩餘$LEFT|H$座可供使用。"
 PRODICTION_MIC_RECEIVED_FROM_EXILE_DONATIONS:0 "目前有$AMOUNT|Y$座工廠由我們扶持的流亡政府提供。"
 PRODUCTION_CIVILIAN_FACTORIES_AVAILABLE:0 "閒置中：$VALUE|Y$"
 PRODUCTION_CIVILIAN_FACTORIES_CURRENTLY:0 "運作中：$VALUE|Y$"
 PRODUCTION_MAX_EFFICIENCY_BASE:0 "基礎上限：$VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_TOT:0 "£prod_eff_cap 生產效率上限：$VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_HINT:0 "£prod_eff_cap 生產效率上限決定了£prod_eff 生產效率的最大值，而上限的最大值可以藉由研發相關的£tech_mod 科技進一步提高。"
 PRODUCTION_RESOURCES_PER_FACTORY:0 "§H每座工廠所需的戰略資源：§!"
 PRODUCTION_MATERIAL_NO_WASTE:0 "使用該種戰略資源的生產線未浪費。" #
 PRODUCTION_MATERIAL_WASTE:0 "使用該種戰略資源的生產線已浪費$WASTE|R2$單位。"
 PRODUCTION_SPEED:0 "生產速率：$SPEED|Y$"
 PRODUCTION_SPEED_MODIFIERS:0 "§Y產量修正：§!"
 INDUSTRIAL_CAPACITY_FACTOR:0 "工廠產量：$VALUE|Y$"
 INDUSTRIAL_CAPACITY_FACTOR_MODIFIERS:0 "工廠產量修正："
 INDUSTRIAL_PROGRESS:0 "$BUILDING|H$$PROGRESS|0H$/$COST|0H$（$VALUE|0%H$）完成。"
 INDUSTRIAL_PROGRESS_REPAIR:0 "$BUILDING|H$維修進度：$PROGRESS|%0H$"
 INDUSTRIAL_BASE_FACTORY_OUTPUT:0 "基礎工廠產量：$VALUE|H$"
 INDUSTRIAL_BASE_SPEED:0 "$FACTORIES|0H$工廠產量：$VALUE|H$"
 PROD_COST_VALUE:0 "£production_cost  $VALUE$"
 NAVPROD_COST_VALUE:0 "£navprod_cost  $VALUE$"
 PRODUCTION_CIVILIAN_FACTORIES_OWNED:0 "國內：$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_BORROWED:0 "國外：§H+§!$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_SUBJECTS:0 "附庸國進貢：§H+§!$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_MASTER:0 "宗主國徵用：$VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_OTHERS:0 "來自其他國家：§H+§!$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_OTHERS:0 "給予其他國家：$VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_DAMAGED:0 "已受損：$VAL|R$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED:2 "$VALUE|0Y$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_FILLED:1 "$AMOUNT|0G$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_UPGRADE:1 "$VALUE|0Y$"
 PRODUCTION_EQUIPMENT_DAILY_BALANCE:0 "每日盈餘：$VALUE|=2Y$"
 PRODUCTION_EQUIPMENT_FILL_ESTIMATION:0 "按照目前的每日盈餘，所有需求都將在$VALUE|0Y$天內得到§Y滿足§!。"
 PRODUCTION_EQUIPMENT_FILLED:0 "目前需求已§G滿足§!"
 PRODUCTION_EQUIPMENT_LOSSES:0 "昨天的裝備損失共計$VALUE|R$單位。"
 PROD_LINE_PLANE_DEST_RESERVES_DUE_TO_MANPOWER:0 "由於§H人力§!不足所以§Y後備§!人力用於§Y增援§!" #
 PROD_LINE_PLANE_DEST_RESERVES:1 "此生產線的產品現已用於§Y儲備§!和§Y庫存§!。"
 PROD_LINE_PLANE_DEST_UPGRADING:2 "此生產線的產品現已用於§Y升級§!和§Y替換§!。"
 PROD_LINE_PLANE_DEST_REINFORCEMENT:2 "此生產線的產品現已用於§Y增援§!和§Y補充§!。"
 PROD_LINE_LAND_DEST_RESERVES:1 "此生產線的產品現已用於§Y儲備§!和§Y庫存§!。"
 PROD_LINE_LAND_DEST_UPGRADING:2 "此生產線的產品現已用於§Y升級§!和§Y替換§!。"
 PROD_LINE_LAND_DEST_REINFORCEMENT:2 "此生產線的產品現已用於§Y增援§!和§Y補充§!。"
 CONFIRM_REMOVE_BUILDING_LEVEL_TITLE:0 "拆除建築"
 CONFIRM_REMOVE_BUILDING_LEVEL_DESC:0 "您確定要§R拆除§!此建築嗎？"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_TITLE:0 "撤銷建築命令"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_DESC:0 "您確定要§R撤銷§!建築工程嗎？"
 CONFIRM_REMOVE_CONVERSION_LEVEL_TITLE:0 "撤銷改建命令"
 CONFIRM_REMOVE_CONVERSION_LEVEL_DESC:0 "您確定要§R撤銷§!改建工程嗎？"
 CONFIRM_ADD_CONVERSION_LEVEL_TITLE:0 "開始改建"
 CONFIRM_ADD_CONVERSION_LEVEL_DESC:0 "您確定要§R改建§!此建築嗎？"
 PRODUCTION_EFFICIENCY_GAIN_BASE:0 "每日基礎收入：$VAL|%Y$"
 PRODUCTION_RESOURCE_FACTOR:0 "缺少資源：$VAL|%+$"
 PRODUCTION_OUTPUT_EXPLAIN:0 "目前有$FACTORIES|Y$座£factory_item 軍事工廠提供£production_cost $OUTPUT|Y$產量。\n$ITEM|Y$\n每單位花費：£production_cost $ITEM_COST|2Y$，目前總產量：$PERTIMEPERIOD$。\n"
 PRODUCTION_OUTPUT_EXPLAIN_NAVAL:0 "目前有$FACTORIES|Y$座£naval_factory_icon 海軍船塢提供£navprod_cost $OUTPUT|Y$產量。\n$ITEM|Y$\n每單位花費：£navprod_cost $ITEM_COST|2Y$，目前總產量：$PERTIMEPERIOD$。\n"
 PRODUCTION_UNITS_PER_DAY:0 "每日$UNITS|Y$單位"
 PRODUCTION_UNITS_PER_WEEK:0 "每週$UNITS|Y$單位"
 PRODUCTION_UNITS_PER_MONTH:0 "每月$UNITS|Y$單位"
 PRODUCTION_UNITS_PER_YEAR:0 "每年$UNITS|Y$單位"
 PRODUCTION_FACTORY_ASSIGN_DESC:1 "點擊左鍵分配$FACTORIES|Y$座£factory_item §Y軍事工廠§!至此生產線。每日總產量將變更為£production_cost $OUTPUT|Y$。"
 PRODUCTION_DOCKYARD_ASSIGN_DESC:1 "點擊左鍵分配$FACTORIES|Y$座£naval_factory_icon §Y海軍船塢§!至此生產線。每日總產量將變更為£navprod_cost $OUTPUT|Y$。"
 PRODUCTION_BASE_OUTPUT:0 "基礎產量：$VALUE|Y$ x$MUL$"
 PRODUCTION_EFF_GAIN_HINT:0 "§Y效率增幅修正：§!"
 CARRIER_AIR_WING_COMPOSITION_TITLE:0 "設定該航母空軍部隊的默認編組"
 CARRIER_AIR_WING_LIMIT_UNDER:0 "$COUNT|Y$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_MATCH:0 "$COUNT|G$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_OVER:0 "$COUNT|R$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_DESC:0 "飛機/機棚空間"
 CARRIER_AIR_WING_LIMIT_DESC_UNDER:0 "§Y此航母有閒置的機棚空間§!"
 CARRIER_AIR_WING_LIMIT_DESC_OVER:0 "§R超過此航母的載機容量。駐紮其中的空軍聯隊將會遭受減成效果§!"
 CARRIER_AIR_WING_INCREASE:0 "增加空軍聯隊的數量\n按住「§GCtrl§!」同時§G點擊左鍵§!，即可增加 §H5§!\n按住「§GShift§!」同時§G點擊左鍵§!，即可增加 §H10§!"
 CARRIER_AIR_WING_DECREASE:0 "減少空軍聯隊的數量\n按住「§GCtrl§!」同時§G點擊左鍵§!，即可減少 §H5§!\n按住「§GShift§!」同時§G點擊左鍵§!，即可減少 §H10§!"
 PRODUCTION_ENTRY_NEW:0 "§G新型§!"
 PRODUCTION_ENTRY_OUTDATED:0 "§H舊型§!"
 PRODUCTION_LINE_CHANGE:0 "§G點擊左鍵，即可§H改變§!生產項目。\n若是改以生產同類裝備的改裝型號，即可保留部分的生產速率。\n§!§R但是截至目前為止的所有生產速率都會重置。§!" #
 PRODUCTION_LINE_CHANGE_NAVAL:0 "§G點擊左鍵§!，即可§H改變§!生產項目。\n§!§R但是您會因此而損失部分的生產速率。§!"
 PRODUCTION_EQUIPMENT_FILTER:0 "小型槍械與大型火火砲"
 PRODUCTION_ARMOR_FILTER:0 "戰甲車輛"
 PRODUCTION_AIR_FILTER:0 "飛行器"
 PRODUCTION_CAPITAL_SHIPS_FILTER:0 "主力艦"
 PRODUCTION_SCREEN_SHIPS_FILTER:0 "護衛艦"
 PRODUCTION_OTHER_SHIPS_FILTER:0 "其他艦種"
 PRODUCTION_LACKING_RESOURCES_FILTER:0 "所需戰略資源已滿"
 PRODUCTION_STOCKPILING_FILTER:0 "用於儲備和庫存"
 PRODUCTION_REINFORCING_FILTER:0 "用於增援和補充"
 PRODUCTION_UPGRADING_FILTER:0 "用於升級和替換"
 PRODUCTION_OUTDATED_FILTER:0 "最新型號"
 PRODUCTION_REFITTING_FILTER:0 "改裝"
 PRODUCTION_FILTER_CLICK_TO_HIDE:0 "§G點擊左鍵§!，即可§R隱藏§!此類別的所有項目。"
 PRODUCTION_FILTER_CLICK_TO_SHOW:0 "§G點擊左鍵§!，即可§G顯示§!此類別的所有項目。"
 PRODUCTION_FILTER_SHIFTCLICK:1 "\n按住「§GShift§!」同時§G點擊左鍵§!，即可§R隱藏§!所有重複項目。"
 PRODUCTION_FILTER_SHIFTCLICK_AGAIN:0 "\n按住「§GShift§!」同時§G點擊左鍵§!，即可§G顯示§!此類別的所有項目。"
 PRODUCTION_FILTER_RIGHTCLICK:0 "\n§G右鍵點擊§!，即可收起此類別的所有項目。"
 PRODUCTION_FILTER_ARMS_FACTORIES:0 "軍事工廠使用"
 PRODUCTION_FILTER_DOCKYARDS:0 "海軍船塢使用"
 PRODUCTION_DRAG_N_DROP:0 "§G點擊左鍵§!並§G拖曳滑鼠§!，即可更改生產項目的§Y優先權§!"
 PRODUCTION_COLLAPSE:2 "§G點擊左鍵§!，即可§Y縮減§!生產線。\n按住「§GCtrl§!」同時§G點擊左鍵§!，即可§Y縮減§!同類生產線。\n按住「§GShift§!」同時§G點擊左鍵§!，即可§Y縮減§!所有生產線。"
 PRODUCTION_EXPAND:2 "§G點擊左鍵§!，即可§Y擴大§!生產線。\n按住「§GCtrl§!」同時§G點擊左鍵§!，即可§Y擴大§!同類生產線。\n按住「§GShift§!」同時§G點擊左鍵§!，即可§Y擴大§!所有生產線。"
 PRODUCTION_FACTORY_SCALE_UP:0 "§G點擊左鍵§!，即可以§Y$SCALE$x§!數量查看。"
 PRODUCTION_FACTORY_SCALE_DOWN:0 "§G點擊左鍵§!，即可以§Y1x§!數量查看。"
 PRODUCTION_ADD_FACTORIES_CLICK:0 "§G點擊左鍵§!，即可添加§Y1§!座工廠\n按住「§GCtrl§!」同時§G點擊左鍵§!，即可添加§Y5§!座工廠\n按住「§GShift§!」同時§G點擊左鍵§!，即可添加§Y10§!座工廠"
 PRODUCTION_SUB_FACTORIES_CLICK:0 "§G點擊左鍵§!，即可移除§Y1§!座工廠\n按住「§GCtrl§!」同時§G點擊左鍵§!，即可移除§Y5§!座工廠\n按住「§GShift§!」同時§G點擊左鍵§!，即可移除§Y10§!座工廠"
 PRODUCTION_ADD_1:0 "§G點擊左鍵§!，即可§Y+1§!"
 PRODUCTION_ADD_5:0 "按住「§GCtrl§!」同時§G點擊左鍵§!，即可§Y+5§!"
 PRODUCTION_ADD_10:0 "按住「§GShift」同時§G點擊左鍵§!，即可§Y+10§!"
 PRODUCTION_SUB_1:0 "§G點擊左鍵§!，即可§Y-1§!"
 PRODUCTION_SUB_5:0 "按住「§GCtrl§!」同時§G點擊左鍵§!，即可§Y-5§!"
 PRODUCTION_SUB_10:0 "按住「§GShift」同時§G點擊左鍵§!，即可§Y-10§!"
 PRODUCTION_ADD_NAVAL_FACTORIES_CLICK:0 "§G點擊左鍵§!，即可§Y+1§!"
 PRODUCTION_SUB_NAVAL_FACTORIES_CLICK:0 "§G點擊左鍵§!，即可§Y-1§!"
 PRODUCTION_CLICK_TO_APPEND_OR_INSERT:0 "§G點擊左鍵§!，即可添加一條生產線至最底部。\n按住「§GShift§!」同時§G點擊左鍵§!，即可添加一條生產線至最頂部。"
 PRODUCTION_NAVAL_DEPLOYMENT_STATE_NAME:0 "$STATE$（$LVL|Y$）"
 PRODUCTION_LINE_CONVERT_NO_EQUIPMENT_IN_STOCK:0 "§R目前沒有我們可以用來轉換的儲備：$VARIANT|H$§!"
 PRODUCTION_LINE_CONVERT_HEADER:0 "改裝儲備"
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION:0 "改裝序列："
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_ENTRY:0 "\n $NUM|Y2$ 單位的$VARIANT|G$（$TYPE$）花費：" ###
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_FREE_ENTRY:0 "\n $NUM|Y2$ 單位的$VARIANT|G$（$TYPE$）"
 PRODUCTION_LINE_CONVERT_RESOURCE_COST_ENTRY:0 "§H$NUM$§! £resources_strip|$FRAME$"
 PRODUCTION_LINE_CONVERT_DESC:1 "這項措施能將庫存中的§H基礎裝備§!、§H過時裝備§!或§H其他裝備§!，以較低的成本改裝為目前生產線所需的現役裝備，直到庫存中的裝備用盡為止。"
 PRODUCTION_LINE_CONVERT_SPEED_TOTAL:1 "改裝速率：§G+§!$SPD|G%0$"
 PRODUCTION_LINE_CONVERT_SPEED_BASE:0 "基礎值：$VAL|Y0%$"
 PRODUCTION_LINE_CONVERT_RES_NEED:0 "改裝$NAME|Y$所需的戰略資源："
 PRODUCTION_LINE_CONVERT_RES_NEED_ENTRY:0 "\n   £resources_strip|$FRAME$：（$NEW|Y0$-$OLD|G0$）=$SUM|R0$"
 PRODUCTION_LINE_SHIP_NAME_ALLOCATE:0 "此名稱尚未分配給任何其他船艦。§G點擊左鍵§!，即可以此名稱命名生產線。"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL_SIMPLE:0 "§H生產許可§!：$VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL:0 "§H授權工廠產出§!\n總計：$VALUE|+%$\nBreakdown："
 LICENSED_EQUIPMENT_TECH_SPEED_REDUCTION:1 "§Y科技差距§!：$TOTAL|+%$\nBase：$BASE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_MODIFIER:1 "§Y授權修正§!：$TOTAL|+%$\nBase：$BASE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NOT_FACTION:0 "§Y未加入授權國陣營§!：$VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NO_LICENSE:0 "§Y缺少授權許可§!：$VALUE|+%$"
 LICENSED_EQUIPMENT_UPGRADE_XP_COST_MODIFIER:0 "許可證裝備：$VAL$"
 LICENSED_PURCHASE_CIC_COST:1 "§Y這項授權花費§!：£civ_factory_output $AMOUNT|Y$"
 PRODUCTION_NAVAL_REPAIRS_LABEL:0 "維修隊列"
 PRODUCTION_NAVAL_NAME_LIST:0 "船艦名稱"
 PRODUCTION_NAVAL_NAME_LIST_BUTTON_FALLBACK:0 "船艦名稱"
 PRODUCTION_NAVAL_NAME_LIST_EMPTY_NOT_ALLOWED:0 "§R不可空白。§!"
 PRODUCTION_NAVAL_NAME_LIST_TOO_FEW_PRODUCED:0 "§R名稱將超出生產隊列中的數量。§!"
 PRODUCTION_NAVAL_NAME_LIST_REMOVE:0 "§G點擊左鍵§!，即可§H移除名字§!"
 PRODUCTION_NAVAL_NAME_LIST_NAME_RESERVED:0 "$NAME|H$正在使用中"
 PRODUCTION_NAVAL_NAME_LIST_ADD_NAME:0 "§G點擊左鍵§!，即可命名下一艘$EQUIPMENT|H$為$NAME|H$。"
 PRODUCTION_NAVAL_NAME_LIST_BUTTON_NAME:0 "下一艘$EQUIPMENT|H$將被命名為$NAME|H$。"
 PRODUCTION_NAVAL_NAME_LIST_BUTTON_CLICK:0 "§G點擊左鍵§!，即可更名。"
 PRODUCTION_SHIP_REFIT_TOTAL_COSTS:0 "§H船艦總花費：$COUNT|T$§!\n"
 PRODUCTION_SHIP_REFIT_BASE_ICCOST:0 "基礎裝備：$ICCOST|H2$"
 PRODUCTION_SHIP_REFIT_MODULE_BUILD_ICCOST:0 "新組件：$ICCOST|H2$"
 PRODUCTION_SHIP_REFIT_MODULE_CONVERT_ICCOST:0 "轉換組件：$ICCOST|H2$"
 PRODUCTION_SHIP_REFIT_MODULE_DISMANTLE_ICCOST:0 "拆除組件：$ICCOST|H2$"
 PRODUCTION_SHIP_REFIT_QUICKEST_TIME:0 "使用最多§H船塢§!需要$DAYS|H$天完成。"
 PRODUCTION_SHIP_REFIT_TOOLTIP_DIFF_HEADER:0 "§H改裝的影響§!"
 PRODUCTION_SHIP_REFIT_TOOLTIP_FROM_VARIANT_HEADER:0 "從$VARIANT$（已選擇$SHIP_COUNT|H$）"
 PRODUCTION_SHIP_REFIT_TOOLTIP_NO_STAT_CHANGES:0 "沒有數據改變"
 PRODUCTION_SHIP_REFIT_TOOLTIP_MORE_VARIANTS:0 "和其他裝備改變（已選擇$SHIP_COUNT|H$）"
 PRODUCTION_SUB_UNIT_FILTER:0 "僅顯示$SUBUNIT|H$（$COUNT|H$）" #
 PRODUCTION_EQUIPMENT_ROLE_NO_FILTER:0 "顯示所有任務"
 PRODUCTION_EQUIPMENT_ROLE_FILTER:0 "僅顯示所有$ROLE|H$" #